### ISSUE TITLE
returned non-zero exit status 25

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#320]
And it sendpayment.py  crashes.
Do I get this error because there's an unconfirmed tx in that depth and it's trying to spend that?

```
[2015/11/15 20:53:48] key=gaplimit
[2015/11/15 20:53:48] 6
[2015/11/15 20:53:48] key=index
[2015/11/15 20:53:48] [[90, 19]]
[2015/11/15 20:53:48] key=index_cache
[2015/11/15 20:53:48] [[90, 19], [17, 11], [11, 14], [13, 8], [7, 20]]
[2015/11/15 20:53:48] key=spent_utxos
[2015/11/15 20:53:48] []
[2015/11/15 20:53:48] key=utxo_selector
[2015/11/15 20:53:48] <function select at 0x7fd3f47e07d0>
[2015/11/15 20:53:48] key=path
[2015/11/15 20:53:48] string: len:19
[2015/11/15 20:53:48] wallets/wallet.json
[2015/11/15 20:53:48] key=storepassword
[2015/11/15 20:53:48] False
[2015/11/15 20:53:48] key=max_mix_depth
[2015/11/15 20:53:48] 1
[2015/11/15 20:53:48] key=imported_privkeys
[2015/11/15 20:53:48] {}
[2015/11/15 20:53:48] Class debug dump, name:SendPayment
[2015/11/15 20:53:48] key=maker_pks
[2015/11/15 20:53:48] {}
[2015/11/15 20:53:48] key=makercount
[2015/11/15 20:53:48] 4
[2015/11/15 20:53:48] key=chooseOrdersFunc
[2015/11/15 20:53:48] <function weighted_order_choose at 0x7fd3f42a7398>
[2015/11/15 20:53:48] key=cjtx
[2015/11/15 20:53:48] <taker.CoinJoinTX object at 0x7fd3f41bb990>
[2015/11/15 20:53:48] key=db
[2015/11/15 20:53:48] <sqlite3.Cursor object at 0x7fd3f40dde30>
[2015/11/15 20:53:48] key=mixdepth
[2015/11/15 20:53:48] 0
[2015/11/15 20:53:48] key=waittime
[2015/11/15 20:53:48] 40.0
[2015/11/15 20:53:48] key=wallet
[2015/11/15 20:53:48] <common.Wallet object at 0x7fd3f4195bd0>
[2015/11/15 20:53:48] key=amount
[2015/11/15 20:53:48] ********
[2015/11/15 20:53:48] key=destaddr
[2015/11/15 20:53:48] string: len:34
[2015/11/15 20:53:48] **************************
[2015/11/15 20:53:48] key=msgchan
[2015/11/15 20:53:48] <irc.IRCMessageChannel object at 0x7fd3f4195d10>
[2015/11/15 20:53:48] key=txfee
[2015/11/15 20:53:48] 10000
[2015/11/15 20:53:48] key=answeryes
[2015/11/15 20:53:48] False
[2015/11/15 20:53:48] Traceback (most recent call last):
  File "sendpayment.py", line 193, in main
    irc.run()
  File "/home/joinmarket/lib/irc.py", line 502, in run
    self.__handle_line(line)
  File "/home/joinmarket/lib/irc.py", line 405, in __handle_line
    self.__handle_privmsg(chunks[0], chunks[2], get_irc_text(line))
  File "/home/joinmarket/lib/irc.py", line 358, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/home/joinmarket/lib/irc.py", line 235, in __on_privmsg
    self.on_sig(nick, sig)
  File "/home/joinmarket/lib/taker.py", line 418, in on_sig
    self.cjtx.add_signature(nick, sig)
  File "/home/joinmarket/lib/taker.py", line 195, in add_signature
    self.finishcallback(self)
  File "sendpayment.py", line 82, in finishcallback
    coinjointx.self_sign_and_push()
  File "/home/joinmarket/lib/taker.py", line 233, in self_sign_and_push
    self.push(self.latest_tx)
  File "/home/joinmarket/lib/taker.py", line 227, in push
    self.txid = common.bc_interface.pushtx(tx)
  File "/home/joinmarket/lib/blockchaininterface.py", line 557, in pushtx
    return self.rpc('sendrawtransaction', [txhex])
  File "/home/joinmarket/lib/blockchaininterface.py", line 437, in rpc
    res = self.jsonRpc.call(method, args)
  File "/home/joinmarket/lib/blockchaininterface.py", line 36, in call
    res = subprocess.check_output(fullCall)
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['/home/bitcoin-0.11.0/bin/bitcoin-cli', '-datadir=/Bitcoin/', 'sendrawtransaction', '***']' returned non-zero exit status 25

done
```

**Comment by AdamISZ** [comment]
A few things you could try: try resubmitting the transaction directly over bitcoin rpc. Most likely you will get error 25 again. Check the bitcoin debug log to see if there is any further error message (unfortunately I think error code 25 is a general verify error message, not too informative, see https://github.com/bitcoin/bitcoin/blob/master/src/rpcprotocol.h#L49

Other than that try to deserialize the transaction and look at the inputs and outputs. It could happen if there was something wrong with one of the inputs/outputs (e.g. zero outputs, dust etc).

It's possible that a spend could fail if an input had already been spent (double spend), but I don't think you'd get that error in that case. I am far from sure though.

**Comment by K1773R** [comment]
is -datadir=/Bitcoin/ even correct?

**Comment by dreboli** [comment]
-datadir is correct, it's just censored

I was running sendpayments one after another, and the second time it started to throw this error every time I tried.
But I didn't dig deeper, maybe later.

**Comment by AdamISZ** [comment]
This can happen (code 25 failed push tx) (I've seen it myself) if one of your makers has recently conducted a transaction with a utxo, but has not yet seen the utxo on the network. There can be appreciable delays especially when the network is stressed and/or the transaction fees are very low (makes it difficult for a tx to propagate); w.r.t to the second, #346 will hopefully help. But fundamentally, this can happen as part of joinmarket's design, because a maker will *not* reserve utxos until he sees they've been broadcast onto the network; if he did, it would represent a trivial DOS opportunity.

Now, I'm not *sure* that that's what happened here; you can (although it's tedious) review the vin txids and indices, and check the status of each utxo on the network. If it's in an unspent transaction already then that would explain it. That's what I saw.

I'm going to close this on the assumption that this understanding is correct, but please feel free to reopen if there's new information.
