### ISSUE TITLE
exception in yield generator

### ISSUE THREAD

**Issue by riclas** [JoinMarket-Org/joinmarket#344]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\joinmarket\lib\blockchaininterface.py", line 239, in run
    txhex = str(txinfo['tx']['hex'])
TypeError: list indices must be integers, not str

**Comment by chris-belcher** [comment]
https://github.com/JoinMarket-Org/joinmarket/blob/master/lib/blockchaininterface.py#L239

Probably blockr.io changed their format.
This would only crash the notify thread and not the main thread.

**Comment by AdamISZ** [comment]
I have been using blockr.io in tests, mainly testnet but also mainnet a couple of times and haven't seen this?

**Comment by riclas** [comment]
this doesn't seem to have been logged so i can't give more information... It hasn't happened again fwiw.

**Comment by chris-belcher** [comment]
Well we can always put code to the effect of

       if 'tx' not in txinfo or 'hex' not in txinfo['tx']:
           recover from error

**Comment by chucklesmcgee** [comment]
Getting something similar:

`Exception` in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/pi/bin/joinmarket/joinmarket/irc.py", line 123, in run
    self.irc.fd.close()
  File "/usr/lib/python2.7/socket.py", line 282, in close
    self._sock.close()
AttributeError: 'NoneType' object has no attribute `'close'`

**Comment by K1773R** [comment]
@chucklesmcgee 
no, this is not related, at all.
your facing a connection issue (closing connection while no connection is active).

**Comment by chucklesmcgee** [comment]
I see. I'm running my own node which remains up and functional. A second script seems unaffected. How can I make the script attempt to reconnect if this error occurs?

**Comment by K1773R** [comment]
open your own issue and stop abusing others...
