### ISSUE TITLE
tumbler crash:  "failed to send on socket"

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#439]
```
$ python tumbler.py --addrcount=2 --wait-time=120 --liquiditywait=120 tumbler.json xxx1 xxx2
...
:00:00,206 [Thread-2    ] [DEBUG]  failed to send on socket
:00:00,239 [MainThread  ] [DEBUG]  key=maker_pks
:00:00,258 [MainThread  ] [DEBUG]  {}
:00:00,273 [MainThread  ] [DEBUG]  key=tumbler_thread
:00:00,285 [MainThread  ] [DEBUG]  <TumblerThread(Thread-3, started daemon -1258294176)>
:00:00,298 [MainThread  ] [DEBUG]  key=cjtx
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/irc.py", line 123, in run
    self.irc.fd.close()
  File "/usr/lib/python2.7/socket.py", line 282, in close
    self._sock.close()
AttributeError: 'NoneType' object has no attribute 'close'

:00:00,311 [MainThread  ] [DEBUG]  <joinmarket.taker.CoinJoinTX object at 0xb6378b70>
:00:00,336 [MainThread  ] [DEBUG]  key=db
:00:00,343 [MainThread  ] [DEBUG]  <sqlite3.Cursor object at 0xb652c420>
:00:00,350 [MainThread  ] [DEBUG]  key=wallet
:00:00,360 [MainThread  ] [DEBUG]  <joinmarket.wallet.Wallet object at 0xb63e0df0>
:00:00,367 [MainThread  ] [DEBUG]  key=msgchan
:00:00,374 [MainThread  ] [DEBUG]  <joinmarket.irc.IRCMessageChannel object at 0xb63e0d50>
:00:00,381 [MainThread  ] [DEBUG]  key=options
:00:00,389 [MainThread  ] [DEBUG]  {'liquiditywait': 120, 'addrcount': 2, 'minmakercount': 2, 'amountpower': 100.0, 'txcountparams': (4, 1), 'mixdepthcount': 4, 'waittime': 120.0, 'txfee': 5000, 'mincjamount': 100000, 'mixdepthsrc': 0, 'makercountrange': (3, 1.5), 'maxcjfee': (0.01, 10000), 'donateamount': 0, 'timelambda': 30, 'mintxcount': 1}
:00:00,397 [MainThread  ] [DEBUG]  Class debug dump, name:CoinJoinTX
:00:00,404 [MainThread  ] [DEBUG]  key=latest_tx
:00:00,412 [MainThread  ] [DEBUG]  None
:00:00,419 [MainThread  ] [DEBUG]  key=total_txfee
:00:00,426 [MainThread  ] [DEBUG]  20000
:00:00,432 [MainThread  ] [DEBUG]  key=cj_amount
:00:00,439 [MainThread  ] [DEBUG]  485841
:00:00,446 [MainThread  ] [DEBUG]  key=crypto_boxes
:00:00,473 [MainThread  ] [DEBUG]  {'Canisojof': ['xxx',
               <libnacl.public.Box object at 0xb6394970>],
 'Wovorijax': ['xxx',
               <libnacl.public.Box object at 0xb6378cd0>]}
:00:00,488 [MainThread  ] [DEBUG]  key=cjfee_total
:00:00,496 [MainThread  ] [DEBUG]  782
:00:00,502 [MainThread  ] [DEBUG]  key=timeout_thread_lock
:00:00,510 [MainThread  ] [DEBUG]  <Condition(<_RLock owner='Thread-8' count=1>, 0)>
:00:00,517 [MainThread  ] [DEBUG]  key=all_responded
:00:00,524 [MainThread  ] [DEBUG]  False
:00:00,531 [MainThread  ] [DEBUG]  key=txid
:00:00,538 [MainThread  ] [DEBUG]  None
:00:00,545 [MainThread  ] [DEBUG]  key=end_timeout_thread
:00:00,552 [MainThread  ] [DEBUG]  False
:00:00,559 [MainThread  ] [DEBUG]  key=timeout_lock
:00:00,568 [MainThread  ] [DEBUG]  <Condition(<_RLock owner=None count=0>, 0)>
:00:00,575 [MainThread  ] [DEBUG]  key=utxos
:00:00,599 [MainThread  ] [DEBUG]  {None: ['xxx:0'],
 'Wovorijax': ['xxx:2']}
:00:00,609 [MainThread  ] [DEBUG]  key=my_change_addr
:00:00,616 [MainThread  ] [DEBUG]  string: len:34
:00:00,623 [MainThread  ] [DEBUG]  xxx
:00:00,630 [MainThread  ] [DEBUG]  key=my_cj_addr
:00:00,637 [MainThread  ] [DEBUG]  string: len:34
:00:00,644 [MainThread  ] [DEBUG]  xxx
:00:00,651 [MainThread  ] [DEBUG]  key=maker_txfee_contributions
:00:00,658 [MainThread  ] [DEBUG]  314
:00:00,667 [MainThread  ] [DEBUG]  key=outputs
:00:00,687 [MainThread  ] [DEBUG]  [{'address': 'xxx', 'value': 54504},
 {'address': 'xxx', 'value': 485841}]
:00:00,698 [MainThread  ] [DEBUG]  key=db
:00:00,705 [MainThread  ] [DEBUG]  <sqlite3.Cursor object at 0xb652c420>
:00:00,712 [MainThread  ] [DEBUG]  key=msgchan
:00:00,720 [MainThread  ] [DEBUG]  <joinmarket.irc.IRCMessageChannel object at 0xb63e0d50>
:00:00,727 [MainThread  ] [DEBUG]  key=auth_addr
:00:00,734 [MainThread  ] [DEBUG]  None
:00:00,740 [MainThread  ] [DEBUG]  key=active_orders
:00:00,799 [MainThread  ] [DEBUG]  {u'Quxayohen': {'cjfee': u'517',
                'counterparty': u'Quxayohen',
                'maxsize': 110100923,
                'minsize': 2731,
                'oid': 0,
                'ordertype': u'absorder',
                'txfee': 150},
 u'Ticizuvaz': {'cjfee': u'0.000999',
                'counterparty': u'Ticizuvaz',
                'maxsize': 4816718561L,
                'minsize': 1201,
                'oid': 0,
                'ordertype': u'relorder',
                'txfee': 1},
 u'Wovorijax': {'cjfee': u'782',
                'counterparty': u'Wovorijax',
                'maxsize': 1713277,
                'minsize': 2731,
                'oid': 0,
                'ordertype': u'absorder',
                'txfee': 314},
 u'jointhor': {'cjfee': u'1500',
               'counterparty': u'jointhor',
               'maxsize': 13010043,
               'minsize': 2731,
               'oid': 0,
               'ordertype': u'absorder',
               'txfee': 1000}}
:00:00,819 [MainThread  ] [DEBUG]  key=wallet
:00:00,829 [MainThread  ] [DEBUG]  <joinmarket.wallet.Wallet object at 0xb63e0df0>
:00:00,838 [MainThread  ] [DEBUG]  key=kp
:00:00,845 [MainThread  ] [DEBUG]  <libnacl.public.SecretKey object at 0xb6378b90>
:00:00,853 [MainThread  ] [DEBUG]  key=nonrespondants
:00:00,862 [MainThread  ] [DEBUG]  [u'Ticizuvaz', u'jointhor', u'Quxayohen']
:00:00,871 [MainThread  ] [DEBUG]  key=input_utxos
:00:00,890 [MainThread  ] [DEBUG]  {'xxx:0': {'address': 'xxx',
                                                                        'value': 1187152}}
:00:00,900 [MainThread  ] [DEBUG]  key=finishcallback
:00:00,908 [MainThread  ] [DEBUG]  <bound method TumblerThread.finishcallback of <TumblerThread(Thread-3, started daemon -1258294176)>>
:00:00,915 [MainThread  ] [DEBUG]  key=choose_orders_recover
:00:00,922 [MainThread  ] [DEBUG]  <bound method TumblerThread.tumbler_choose_orders of <TumblerThread(Thread-3, started daemon -1258294176)>>
:00:00,942 [MainThread  ] [DEBUG]  Traceback (most recent call last):
  File "tumbler.py", line 576, in main
    irc.run()
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/irc.py", line 649, in run
    self.on_disconnect()
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/taker.py", line 495, in on_disconnect
    self.db.execute('DELETE FROM orderbook;')
ProgrammingError: Recursive use of cursors not allowed.

done
```

develop branch
Raspi 1 b+, raspbian

Joinmarket.cfg 
```
[BLOCKCHAIN]
blockchain_source = bitcoin-rpc
rpc_host = localhost
rpc_port = 8332
rpc_user = xxx
rpc_password = xxx

network = mainnet

[MESSAGING]
socks5 = true
host = a2jutl5hpza43yog.onion
channel = joinmarket-pit
port = 6697
usessl = true
socks5_host = 127.0.0.1
socks5_port = 9050
maker_timeout_sec = 100

[POLICY]
merge_algorithm = default
tx_fees = 3
```

~/.bitcoin/bitcoin.conf 
```
server=1
listen=0
rpcuser=xxx
rpcpassword=xxx

#joinmarket
walletnotify=curl -sI --connect-timeout 100 http://localhost:62602/walletnotify?%s
alertnotify=curl -sI --connect-timeout 100 http://localhost:62602/alertnotify?%s
```

```
$ /usr/local/bin/bitcoind -prune=550 -daemon -proxy=127.0.0.1:9050 -pid=/home/pi/bitcoind.pid -datadir=/home/pi/.bitcoin/ -dbcache=4 -checkblocks=1 -blocksonly=1
```

**Comment by chris-belcher** [comment]
Looks like it was caused by the internet disconnecting which made the script call on_disconnected() which then tried to delete the internal orderbook. That was asynchronous access to the database which raised the exception `ProgrammingError: Recursive use of cursors not allowed.` [According to this stackoverflow page](http://stackoverflow.com/questions/26629080/python-and-sqlite3-programmingerror-recursive-use-of-cursors-not-allowed) we can fix it using threading locks for all access to that database.
