### ISSUE TITLE
Tumbler crash: Socks5Error: 'TTL expired'

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#452]
My system time wasn't off (as I understand it might be a cause for this error) even though that might happen on the Pi.

```
TIMESTAMP_0000000001469 [MainThread  ] [DEBUG]  key=wallet
TIMESTAMP_0000000001470 [MainThread  ] [DEBUG]  <joinmarket.wallet.Wallet object at 0xb6399d70>
TIMESTAMP_0000000001471 [MainThread  ] [DEBUG]  key=kp
TIMESTAMP_0000000001472 [MainThread  ] [DEBUG]  <libnacl.public.SecretKey object at 0xb6346390>
TIMESTAMP_0000000001473 [MainThread  ] [DEBUG]  key=nonrespondants
TIMESTAMP_0000000001474 [MainThread  ] [DEBUG]  []
TIMESTAMP_0000000001475 [MainThread  ] [DEBUG]  key=input_utxos
TIMESTAMP_0000000001476 [MainThread  ] [DEBUG]  {u'TXID_INDEX_00000000000000000000000000000000000000000000000000000586': {'address': u'1ADDRESS_00000000000000000000616',
                                                                         'value': VALUE_0000000594},
 'TXID_INDEX_00000000000000000000000000000000000000000000000000000587': {'address': '1ADDRESS_00000000000000000000617',
                                                                        'value': VALUE_0000000595},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000588': {'address': u'1ADDRESS_00000000000000000000618',
                                                                         'value': VALUE_0000000596},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000589': {'address': u'1ADDRESS_00000000000000000000619',
                                                                         'value': VALUE_0000000597},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000590': {'address': u'1ADDRESS_00000000000000000000620',
                                                                         'value': VALUE_0000000598},
 'TXID_INDEX_00000000000000000000000000000000000000000000000000000591': {'address': '1ADDRESS_00000000000000000000621',
                                                                        'value': VALUE_0000000599},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000592': {'address': u'1ADDRESS_00000000000000000000622',
                                                                         'value': VALUE_0000000600},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000593': {'address': u'1ADDRESS_00000000000000000000623',
                                                                         'value': VALUE_0000000601}}
TIMESTAMP_0000000001477 [MainThread  ] [DEBUG]  key=finishcallback
TIMESTAMP_0000000001478 [MainThread  ] [DEBUG]  <bound method TumblerThread.finishcallback of <TumblerThread(TumblerThread, started daemon -1259342752)>>
TIMESTAMP_0000000001479 [MainThread  ] [DEBUG]  key=choose_orders_recover
TIMESTAMP_0000000001480 [MainThread  ] [DEBUG]  None
TIMESTAMP_0000000001481 [MainThread  ] [DEBUG]  Traceback (most recent call last):
  File "tumbler.py", line 575, in main
    irc.run()
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/irc.py", line 632, in run
    self.sock.connect(self.serverport)
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/socks.py", line 391, in connect
    self.__negotiatesocks5(destpair[0], destpair[1])
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/socks.py", line 255, in __negotiatesocks5
    raise Socks5Error(_socks5errors[min(9, ord(resp[1]))])
Socks5Error: 'TTL expired'
```

/var/log/tor/log
```
Tried for 120 seconds to get a connection to [scrubbed]:6697. Giving up. (waiting for circuit)
```

**Comment by chris-belcher** [comment]
These scripts shouldn't be crashed by a network error, they should swallow the error and then try to reconnect a couple of seconds later.

This crash should be fixed by making Socks5Error a subclass of IOError.

**Comment by dreboli** [comment]
And an other one
```
disconnected irc
[MainThread  ] [DEBUG]  connecting
[MainThread  ] [DEBUG]  Using socks5 proxy 127.0.0.1:9050
AttributeError("'NoneType' object has no attribute 'close'",)
[MainThread  ] [DEBUG]  CRASHING, DUMPING EVERYTHING
...
[MainThread  ] [DEBUG]  Traceback (most recent call last):
  File "tumbler.py", line 575, in main
    irc.run()
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/irc.py", line 632, in run
    self.sock.connect(self.serverport)
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/socks.py", line 391, in connect
    self.__negotiatesocks5(destpair[0], destpair[1])
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/socks.py", line 255, in __negotiatesocks5
    raise Socks5Error(_socks5errors[min(9, ord(resp[1]))])
Socks5Error: 'Host unreachable'

done
Exception in thread PingThread (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/home/pi/joinmarket_0.1.3_develop/joinmarket/irc.py", line 163, in run
  File "/usr/lib/python2.7/threading.py", line 355, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

**Comment by chris-belcher** [comment]
Fix here, scripts should just gracefully recover now. https://github.com/JoinMarket-Org/joinmarket/commit/74980fca658ce6d83bbaa494a0d503edd63741b2

I'll leave open for a bit to check and then close
