### ISSUE TITLE
Exception: ErrorException [ 8 ]: Array to string conversion ~ SYSPATH/classes/Kohana/Log/Writer.php [ 81 ]

### ISSUE THREAD

**Issue by the9ull** [JoinMarket-Org/joinmarket#457]
I'm using the version 0.1.3.
I get this error on startup of the yield-generator-mixdepth.

````2016-03-10 08:07:22,643 [MainThread  ] [DEBUG]  downloading wallet history
Traceback (most recent call last):
  File "./wallet-tool.py", line 106, in <module>
    jm_single().bc_interface.sync_wallet(wallet)
  File "/path/joinmarket/blockchaininterface.py", line 76, in sync_wallet
    self.sync_addresses(wallet)
  File "/path/joinmarket/blockchaininterface.py", line 150, in sync_addresses
    res = btc.make_request(blockr_url + ','.join(addrs))
  File "/path/bitcoin/bci.py", line 23, in make_request
    raise Exception(p)
Exception: ErrorException [ 8 ]: Array to string conversion ~ SYSPATH/classes/Kohana/Log/Writer.php [ 81 ]````

**Comment by AdamISZ** [comment]
Old, closing, feel free to re-open if issue persists on latest version.
