### ISSUE TITLE
total coinjoin fee = 6.97e-05%

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#460]
```
chosen orders = 
{'counterparty': u'Samisanij', 'ordertype': u'relorder', 'oid': 1, 'minsize': 43750000, 'txfee': 33, 'maxsize': 877759034, 'cjfee': u'8E-7'}
chosen orders to fill {u'Samisanij': {'counterparty': u'Samisanij', 'ordertype': u'relorder', 'oid': 1, 'minsize': 43750000, 'txfee': 33, 'maxsize': 877759034, 'cjfee': u'8E-7'}} totalcjfee=221
2016- [TimeoutThrea] [DEBUG]  total coinjoin fee = 6.97e-05%
send with these orders? (y/n):2016- [MainThread  ] [DEBUG]  <<pubmsg nick=Rafewojug message=!orderbook
n
2016-[TimeoutThrea] [DEBUG]  ending
Exception in thread TimeoutThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/null/Downloads/joinmarket_0.1.3_develop/joinmarket/taker.py", line 403, in run
    self.cjtx.recover_from_nonrespondants()
  File "/home/null/Downloads/joinmarket_0.1.3_develop/joinmarket/taker.py", line 356, in recover_from_nonrespondants
    for nick, order in new_orders.iteritems():
AttributeError: 'NoneType' object has no attribute 'iteritems'
```

**Comment by chris-belcher** [comment]
It looks like you pressed no, so of course it crashed/ended ?

**Comment by dreboli** [comment]
I pressed no only after I've seen `total coinjoin fee = 6.97e-05%` which is not readable to me.

**Comment by chris-belcher** [comment]
It means 0.0000697 %

Yes I appreciate not everyone will know how to read scientific notation.

**Comment by raedah** [comment]
`'%.8f' % f`
