### ISSUE TITLE
'Wallet' object has no attribute 'update_index_cache'

### ISSUE THREAD

**Issue by dreboli** [JoinMarket-Org/joinmarket#509]
Error message:
```
 [TumblerThrea] [DEBUG]  rpc: getaccount ['CENSORED']
Exception in thread TumblerThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 367, in run
    self.init_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 322, in init_tx
    self.taker.wallet.update_index_cache()
AttributeError: 'Wallet' object has no attribute 'update_index_cache'

```

Scrubbed log:
```
TIMESTAMP_0000000000001 [MainThread  ] [DEBUG]  starting tumbler
TIMESTAMP_0000000000002 [MainThread  ] [DEBUG]  connecting to irc
TIMESTAMP_0000000000003 [PingThread  ] [DEBUG]  starting ping thread
TIMESTAMP_0000000000004 [MainThread  ] [DEBUG]  connecting
TIMESTAMP_0000000000005 [ThrottleThre] [DEBUG]  starting throttle thread
TIMESTAMP_0000000000006 [MainThread  ] [DEBUG]  Using socks5 proxy 127.0.0.1:9050
TIMESTAMP_0000000000007 [MainThread  ] [DEBUG]  Connected to IRC and joined channel
TIMESTAMP_0000000000008 [MainThread  ] [DEBUG]  >>pubmsg !orderbook
TIMESTAMP_0000000000009 [TumblerThrea] [DEBUG]  waiting for all orders to certainly arrive
TIMESTAMP_0000000000010 [MainThread  ] [DEBUG]  <<privmsg nick=Padequbix message=!absorder 0 2731 9372270 1000 1781!relorder 1 9372271 28440514 1000 0.00018!relorder 2 28440515 58701794 1000 0.00019!relorder 3 58701795 515486845 1000 0.00020
TIMESTAMP_0000000000011 [MainThread  ] [DEBUG]  <<privmsg nick=pocketChange message=!relorder 0 119999999 167507394 1000 0.00001
TIMESTAMP_0000000000012 [MainThread  ] [DEBUG]  <<privmsg nick=Peracuxiy message=!absorder 0 2731 74997270 500 1500!relorder 1 74997271 490072118 500 0.00004!relorder 2 490072119 673810927 500 0.00003
TIMESTAMP_0000000000013 [MainThread  ] [DEBUG]  <<privmsg nick=Vefuboqar message=!absorder 2 100000000 547935076 0 14305!absorder 1 2730 99999999 0 10000
TIMESTAMP_0000000000014 [MainThread  ] [DEBUG]  <<privmsg nick=mrshodler message=!absorder 0 2731 3747270 500 3750!relorder 1 3747271 3963880 500 0.0002!relorder 2 3963881 4059313 500 0.0004!relorder 3 4059314 23645929 500 0.0005!relorder 4 23645930 268459207 500 0.0007!relorder 5 268459208 900096983 500 0.001
TIMESTAMP_0000000000015 [MainThread  ] [DEBUG]  <<privmsg nick=Noduxaxud message=!absorder 0 258353 444443 0 1!relorder 1 444444 14020586 0 4.5e-06!relorder 2 14020586 27782819 0 6.7e-06!relorder 3 27782819 41545052 0 8.9e-06!relorder 4 41545052 69069518 0 1.12e-05!relorder 5 69069518 110356218 0 1.56e-05!relorder 6 110356218 179167383 0 2.23e-05
TIMESTAMP_0000000000016 [MainThread  ] [DEBUG]  <<privmsg nick=Cumikovex message=!absorder 0 2731 68179088 5000 8864!relorder 1 68179089 263349665 5000 0.00014!relorder 2 263349666 264397367 5000 0.00015
TIMESTAMP_0000000000017 [MainThread  ] [DEBUG]  <<privmsg nick=Xoxubuvev message=!absorder 0 262136 43931663 2064 2065!absorder 1 43931663 87601189 2175 2176!absorder 2 87601189 131270716 2287 2288!absorder 3 131270716 193548386 2398 2399!relorder 4 193548387 218609770 2398 1.24e-05!relorder 5 218609770 349618350 2620 1.79e-05!relorder 6 349618350 567965984 2954 2.61e-05!relorder 7 567965984 917322197 3511 3.99e-05!relorder 8 917322197 1485026045 4401 6.18e-05
TIMESTAMP_0000000000018 [MainThread  ] [DEBUG]  <<privmsg nick=Zowocexit message=!absorder 0 2731 12998333 1000 1500
TIMESTAMP_0000000000019 [MainThread  ] [DEBUG]  <<privmsg nick=Nipumigux message=!absorder 1 2730 99999999 0 6000!absorder 2 100000000 425365388 0 12500
TIMESTAMP_0000000000020 [MainThread  ] [DEBUG]  <<privmsg nick=Xehanort message=!absorder 0 152838 2634093 44 143!absorder 1 2634093 5115347 156 255!absorder 2 5115347 7596602 268 367!absorder 3 7596602 12559112 380 479!absorder 4 12559112 20002876 604 703!absorder 5 20002876 32409149 939 1038!absorder 6 32409149 46754384 1499 1598!relorder 7 46754385 52259187 1499 3.42e-05!relorder 8 52259187 84515498 2394 5.21e-05!relorder 9 84515498 136621847 3849 8.13e-05
TIMESTAMP_0000000000021 [MainThread  ] [DEBUG]  <<privmsg nick=Lobocuyay message=!absorder 1 20000000 97668108 0 5000!relorder 0 20000000 108967595 0 7.5e-05
TIMESTAMP_0000000000022 [MainThread  ] [DEBUG]  <<privmsg nick=Tafiralen message=!relorder 0 240000 133490786 1000 0.005
TIMESTAMP_0000000000023 [MainThread  ] [DEBUG]  <<privmsg nick=Qohifaxub message=!relorder 0 5714285 207739832 100 0.000021
TIMESTAMP_0000000000024 [MainThread  ] [DEBUG]  <<privmsg nick=Puyakofad message=!relorder 0 35733333 32035689647 134 0.0000045
TIMESTAMP_0000000000025 [MainThread  ] [DEBUG]  <<privmsg nick=Tikonurem message=!absorder 0 12230 12230 0 0!absorder 1 209163 486259 77 376!absorder 2 486259 763355 429 728!absorder 3 763355 1040451 780 1079!absorder 4 1040451 1594643 1132 1431!absorder 5 1594643 2425931 1835 2134!absorder 6 2425931 3811410 2890 3189!absorder 7 3811410 6028178 4648 4947
TIMESTAMP_0000000000026 [MainThread  ] [DEBUG]  <<privmsg nick=veqtrus-cj message=!absorder 0 20000 14765190 5000 5500
TIMESTAMP_0000000000027 [MainThread  ] [DEBUG]  <<privmsg nick=Qacunomiv message=!absorder 0 2731 68179088 5000 37568!relorder 1 68179089 236649226 5000 0.00018!relorder 2 236649227 419828732 5000 0.00028!relorder 3 419828733 1618205089 5000 0.00038!relorder 4 1618205090 2996075030 5000 0.000551
TIMESTAMP_0000000000028 [MainThread  ] [DEBUG]  <<privmsg nick=Haqecoxib message=!relorder 0 10909090 209015594 1000 0.00011
TIMESTAMP_0000000000029 [MainThread  ] [DEBUG]  <<privmsg nick=Maciyepar message=!relorder 0 2000000 1788513521 1000 0.00144
TIMESTAMP_0000000000030 [MainThread  ] [DEBUG]  <<privmsg nick=Woxupowiq message=!absorder 0 2731 10047270 201 502!relorder 1 10047271 61217139 201 0.00003!relorder 2 61217140 73492606 201 0.00004!relorder 3 73492607 124616867 201 0.00005
TIMESTAMP_0000000000031 [MainThread  ] [DEBUG]  <<privmsg nick=Hinacoyoh message=!absorder 0 100000 8604674 50 125
TIMESTAMP_0000000000032 [MainThread  ] [DEBUG]  <<privmsg nick=Fitiyovuf message=!absorder 0 177698 2142496 65 66!absorder 1 2142496 4107294 298 299!absorder 2 4107294 6072091 531 532!absorder 3 6072091 10001687 764 765!absorder 4 10001687 15896080 1230 1231!absorder 5 15896080 25720069 1929 1930!absorder 6 25720069 41438451 3095 3096!absorder 7 41438451 66980822 4959 4960
TIMESTAMP_0000000000033 [MainThread  ] [DEBUG]  <<privmsg nick=bitjoin message=!relorder 1 13633634 20344104 1000 0.00014!relorder 2 20344105 23562761 1000 0.00015!absorder 0 2731 13633633 1000 1773
TIMESTAMP_0000000000034 [MainThread  ] [DEBUG]  <<privmsg nick=Gupimomig message=!absorder 0 236324 46687668 435 879!absorder 1 46687668 93139012 569 1013!absorder 2 93139012 139590355 702 1146!absorder 3 139590355 232493043 836 1280!absorder 4 232493043 336521738 1103 1547!relorder 5 336521739 371847074 1103 4.6e-06!relorder 6 371847074 604103793 1503 5.4e-06!relorder 7 604103793 975714543 2171 6.7e-06
TIMESTAMP_0000000000035 [MainThread  ] [DEBUG]  <<privmsg nick=Qogegivej message=!absorder 0 231040 60494276 0 3000!absorder 1 60494276 120757513 0 3000!absorder 2 120757513 181020749 0 3000!absorder 3 181020749 188742137 0 3000!relorder 4 188742138 301547222 0 1.59e-05!relorder 5 301547222 482336931 0 2.38e-05!relorder 6 482336931 783653112 0 3.57e-05!relorder 7 783653112 1265759003 0 5.55e-05
TIMESTAMP_0000000000036 [MainThread  ] [DEBUG]  <<privmsg nick=Mopimodon message=!relorder 1 53568699 69992158 1000 0.00012!absorder 0 2731 53568698 1000 1554
TIMESTAMP_0000000000037 [MainThread  ] [DEBUG]  <<privmsg nick=Viguxeqig_ message=!absorder 0 338485 13019999 0 650!relorder 1 13020000 1106605067 0 5e-05!relorder 2 1106605067 2212871649 0 0.0001!relorder 3 2212871649 3319138231 0 0.000189
TIMESTAMP_0000000000038 [MainThread  ] [DEBUG]  <<privmsg nick=kantor message=!absorder 0 2731 5018203 1000 1500
TIMESTAMP_0000000000039 [MainThread  ] [DEBUG]  <<privmsg nick=Kotatasep_ message=!absorder 0 74192 75049999 0 1500!relorder 1 75050000 223312471 0 2e-05!relorder 2 223312471 446550749 0 9.9e-05!relorder 3 446550749 669789028 0 0.000149
TIMESTAMP_0000000000040 [MainThread  ] [DEBUG]  <<privmsg nick=Johacowuz message=!relorder 0 0 2551895562 0 0.00000002
TIMESTAMP_0000000000041 [MainThread  ] [DEBUG]  Johacowuz has dusty minsize, capping at 2730
TIMESTAMP_0000000000042 [MainThread  ] [DEBUG]  <<privmsg nick=Nifasofen message=!absorder 0 2230556 8604674 50 125!absorder 1 7596602 12559112 380 479!absorder 2 12559112 20002876 604 703!absorder 3 20002876 32409149 939 1038!absorder 4 32409149 46754384 1499 1598!absorder 5 46687668 93139012 569 1013!absorder 6 93139012 139590355 702 1146!absorder 7 139590355 232493043 836 1280!absorder 8 232493043 336521738 1103 1547
TIMESTAMP_0000000000043 [MainThread  ] [DEBUG]  <<privmsg nick=plescoi message=!absorder 0 89171 675446 45 545!absorder 1 675446 1261722 248 748!absorder 2 1261722 1847997 450 950!absorder 3 1847997 3020548 653 1153!absorder 4 3020548 4779375 1058 1558!absorder 5 4779375 7710752 1665 2165!absorder 6 7710752 12400955 2678 3178!absorder 7 12400955 20022536 4298 4798
TIMESTAMP_0000000000044 [MainThread  ] [DEBUG]  <<privmsg nick=Cukakobiz message=!absorder 2 10000000 59795544 0 4276!absorder 1 2730 9999999 0 3550
TIMESTAMP_0000000000045 [MainThread  ] [DEBUG]  <<privmsg nick=Yavazobup message=!relorder 0 300000 214300164 1000 0.005
TIMESTAMP_0000000000046 [MainThread  ] [DEBUG]  <<privmsg nick=Nosehovon message=!absorder 1 15000 3305799 970 1870!absorder 2 15000 6611598 1240 3190!absorder 3 15000 9917397 1510 4509!absorder 4 15000 13223196 1780 5830!absorder 5 15000 16528995 2050 7150!absorder 6 15000 19834794 2320 8470!absorder 7 15000 23140593 2589 9500
TIMESTAMP_0000000000047 [MainThread  ] [DEBUG]  <<privmsg nick=marketeer message=!absorder 5 1000000000 2499999999 0 7704!absorder 4 500000000 999999999 0 4280!absorder 3 200000000 499999999 0 7987!absorder 6 2500000000 4358944833 0 8916!absorder 2 100000000 199999999 0 472!absorder 1 10000 99999999 0 1600
TIMESTAMP_0000000000048 [MainThread  ] [DEBUG]  <<privmsg nick=Weyoqevoz_ message=!absorder 0 10000 20609999 1060 2060!relorder 1 20610000 10004344126 1060 0.0001
TIMESTAMP_0000000000049 [MainThread  ] [DEBUG]  <<privmsg nick=Nifasofen message=!absorder 9 200000000 487511220 0 7987!relorder 10 10831517 16114054 0 7.8e-06!relorder 11 14020586 27782819 0 6.7e-06!relorder 12 46754385 52259187 1499 3.42e-05!relorder 13 10047271 61217139 201 3e-05!relorder 14 6000000 8604674 500 0.0001!relorder 15 10007999 451974354 834 0.0001!relorder 16 300000000 487511220 1000 4e-06!relorder 17 2230556 133490786 1000 0.005
TIMESTAMP_0000000000050 [MainThread  ] [DEBUG]  <<privmsg nick=Jiwemiluk message=!absorder 0 56193 167644 95 194!absorder 1 167644 279095 402 501!absorder 2 279095 390547 709 808!absorder 3 390547 613449 1016 1115!absorder 4 613449 947803 1631 1730!absorder 5 947803 1505059 2552 2651!absorder 6 1505059 2396669 4088 4187
TIMESTAMP_0000000000051 [TumblerThrea] [DEBUG]  relorder fee = 4e-06
TIMESTAMP_0000000000052 [TumblerThrea] [DEBUG]  uses 33 makers, at 0.0004% per maker, estimated total cost 0.013%
TIMESTAMP_0000000000053 [TumblerThrea] [DEBUG]  starting
TIMESTAMP_0000000000054 [TumblerThrea] [DEBUG]  get_utxos_by_mixdepth = 
{0: {u'TXID_INDEX_00000000000000000000000000000000000000000000000000000001': {'address': u'1ADDRESS_00000000000000000000001',
                                                                             'value': VALUE_0000000001},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000002': {'address': u'1ADDRESS_00000000000000000000002',
                                                                             'value': VALUE_0000000002},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000003': {'address': u'1ADDRESS_00000000000000000000003',
                                                                             'value': VALUE_0000000003},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000004': {'address': u'1ADDRESS_00000000000000000000004',
                                                                             'value': VALUE_0000000004},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000005': {'address': u'1ADDRESS_00000000000000000000005',
                                                                             'value': VALUE_0000000005},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000006': {'address': u'1ADDRESS_00000000000000000000006',
                                                                             'value': VALUE_0000000006},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000007': {'address': u'1ADDRESS_00000000000000000000007',
                                                                             'value': VALUE_0000000007},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000008': {'address': u'1ADDRESS_00000000000000000000008',
                                                                             'value': VALUE_0000000008},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000009': {'address': u'1ADDRESS_00000000000000000000009',
                                                                             'value': VALUE_0000000009},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000010': {'address': u'1ADDRESS_00000000000000000000010',
                                                                             'value': VALUE_0000000010},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000011': {'address': u'1ADDRESS_00000000000000000000011',
                                                                             'value': VALUE_0000000011},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000012': {'address': u'1ADDRESS_00000000000000000000012',
                                                                             'value': VALUE_0000000012},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000013': {'address': u'1ADDRESS_00000000000000000000013',
                                                                             'value': VALUE_0000000013},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000014': {'address': u'1ADDRESS_00000000000000000000014',
                                                                             'value': VALUE_0000000014},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000015': {'address': u'1ADDRESS_00000000000000000000015',
                                                                             'value': VALUE_0000000015},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000016': {'address': u'1ADDRESS_00000000000000000000016',
                                                                             'value': VALUE_0000000016},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000017': {'address': u'1ADDRESS_00000000000000000000017',
                                                                             'value': VALUE_0000000017},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000018': {'address': u'1ADDRESS_00000000000000000000018',
                                                                             'value': VALUE_0000000018},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000019': {'address': u'1ADDRESS_00000000000000000000019',
                                                                             'value': VALUE_0000000019},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000020': {'address': u'1ADDRESS_00000000000000000000020',
                                                                             'value': VALUE_0000000020},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000021': {'address': u'1ADDRESS_00000000000000000000021',
                                                                             'value': VALUE_0000000021},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000022': {'address': u'1ADDRESS_00000000000000000000022',
                                                                             'value': VALUE_0000000022},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000023': {'address': u'1ADDRESS_00000000000000000000023',
                                                                             'value': VALUE_0000000023},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000024': {'address': u'1ADDRESS_00000000000000000000024',
                                                                             'value': VALUE_0000000024},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000025': {'address': u'1ADDRESS_00000000000000000000025',
                                                                             'value': VALUE_0000000025},
     u'TXID_INDEX_00000000000000000000000000000000000000000000000000000026': {'address': u'1ADDRESS_00000000000000000000026',
                                                                             'value': VALUE_0000000026}},
 1: {},
 2: {},
 3: {}}
TIMESTAMP_0000000000055 [TumblerThrea] [DEBUG]  rpc: getaccount ['1ADDRESS_00000000000000000000027']
TIMESTAMP_0000000000056 [MainThread  ] [DEBUG]  <<pubmsg nick=tornado message=!absorder 0 2731 13758737 1000 1651!relorder 1 13758738 36548189 1000 0.000149 ~
TIMESTAMP_0000000000057 [MainThread  ] [DEBUG]  <<pubmsg nick=kantor message=!absorder 0 2731 5018203 1000 1500 ~
TIMESTAMP_0000000000058 [MainThread  ] [DEBUG]  <<pubmsg nick=Mopimodon message=!absorder 0 2731 53568698 1000 1554!relorder 1 53568699 70092158 1000 0.00012 ~
TIMESTAMP_0000000000059 [MainThread  ] [DEBUG]  <<pubmsg nick=bitjoin message=!absorder 0 2731 13633633 1000 1773!relorder 1 13633634 20444104 1000 0.00014!relorder 2 20444105 23562761 1000 0.00015 ~
TIMESTAMP_0000000000060 [MainThread  ] [DEBUG]  <<pubmsg nick=Yiqipixix message=!orderbook
TIMESTAMP_0000000000061 [MainThread  ] [DEBUG]  <<pubmsg nick=Johacowuz message=!relorder 0 0 2479976382 0 0.00000002 ~
TIMESTAMP_0000000000062 [MainThread  ] [DEBUG]  Johacowuz has dusty minsize, capping at 2730
TIMESTAMP_0000000000063 [MainThread  ] [DEBUG]  <<pubmsg nick=Qacunomiv message=!absorder 0 2731 68179088 5000 37568!relorder 2 236649227 491747913 5000 0.00028!relorder 3 491747914 1618205089 5000 0.00038 ~
TIMESTAMP_0000000000064 [MainThread  ] [DEBUG]  <<pubmsg nick=marketeer message=!absorder 1 10000 99999999 0 1750 ~
TIMESTAMP_0000000000065 [MainThread  ] [DEBUG]  <<pubmsg nick=Qohifaxub message=!relorder 0 5714285 233780984 100 0.000021 ~
TIMESTAMP_0000000000066 [MainThread  ] [DEBUG]  <<pubmsg nick=Puyakofad message=!relorder 0 35733333 32035689647 134 0.0000045 ~
TIMESTAMP_0000000000067 [MainThread  ] [DEBUG]  <<pubmsg nick=Mopimodon message=!absorder 0 2731 53568698 1000 1554 ~
TIMESTAMP_0000000000068 [MainThread  ] [DEBUG]  <<pubmsg nick=Yoticewuh message=!relorder 0 10007999 451974354 834 0.0001 ~
TIMESTAMP_0000000000069 [MainThread  ] [DEBUG]  <<pubmsg nick=Mopimodon message=!absorder 0 2731 53568698 1000 1554 ~
TIMESTAMP_0000000000070 [MainThread  ] [DEBUG]  <<pubmsg nick=Nosehovon message=!absorder 1 15000 3305799 970 1870!absorder 2 15000 6611598 1240 3190!absorder 3 15000 9917397 1510 4509!absorder 4 15000 13223196 1780 5830!absorder 5 15000 16528995 2050 7150!absorder 6 15000 19834794 2320 8470!absorder 7 15000 23140593 2589 9500 ~
TIMESTAMP_0000000000071 [MainThread  ] [DEBUG]  <<pubmsg nick=Cayuhuqij message=!orderbook
TIMESTAMP_0000000000072 [MainThread  ] [DEBUG]  <<pubmsg nick=bitjoin message=!absorder 0 2731 13633633 1000 1773 ~
TIMESTAMP_0000000000073 [MainThread  ] [DEBUG]  <<pubmsg nick=jointhor message=!absorder 0 2731 9906353 1000 1500 ~
TIMESTAMP_0000000000074 [MainThread  ] [DEBUG]  <<pubmsg nick=bitjoin message=!absorder 0 2731 13633633 1000 1773!relorder 1 13633634 22243965 1000 0.00014!relorder 2 22243966 23562761 1000 0.00015 ~
TIMESTAMP_0000000000075 [MainThread  ] [DEBUG]  <<pubmsg nick=Taliqaram message=!orderbook
TIMESTAMP_0000000000076 [MainThread  ] [DEBUG]  <<pubmsg nick=Noduxaxud message=!relorder 1 444444 14159037 0 4.5e-06!relorder 2 14159037 28059721 0 6.7e-06!relorder 3 28059721 41960405 0 8.9e-06!relorder 4 41960405 69761773 0 1.12e-05!relorder 5 69761773 111463824 0 1.56e-05!relorder 6 111463824 180967244 0 2.23e-05 ~
TIMESTAMP_0000000000077 [MainThread  ] [DEBUG]  CRASHING, DUMPING EVERYTHING
TIMESTAMP_0000000000078 [MainThread  ] [DEBUG]  Class debug dump, name:Wallet
TIMESTAMP_0000000000079 [MainThread  ] [DEBUG]  key=unspent
TIMESTAMP_0000000000080 [MainThread  ] [DEBUG]  {u'TXID_INDEX_00000000000000000000000000000000000000000000000000000027': {'address': u'1ADDRESS_00000000000000000000028',
                                                                         'value': VALUE_0000000027},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000028': {'address': u'1ADDRESS_00000000000000000000029',
                                                                         'value': VALUE_0000000028},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000029': {'address': u'1ADDRESS_00000000000000000000030',
                                                                         'value': VALUE_0000000029},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000030': {'address': u'1ADDRESS_00000000000000000000031',
                                                                         'value': VALUE_0000000030},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000031': {'address': u'1ADDRESS_00000000000000000000032',
                                                                         'value': VALUE_0000000031},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000032': {'address': u'1ADDRESS_00000000000000000000033',
                                                                         'value': VALUE_0000000032},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000033': {'address': u'1ADDRESS_00000000000000000000034',
                                                                         'value': VALUE_0000000033},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000034': {'address': u'1ADDRESS_00000000000000000000035',
                                                                         'value': VALUE_0000000034},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000035': {'address': u'1ADDRESS_00000000000000000000036',
                                                                         'value': VALUE_0000000035},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000036': {'address': u'1ADDRESS_00000000000000000000037',
                                                                         'value': VALUE_0000000036},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000037': {'address': u'1ADDRESS_00000000000000000000038',
                                                                         'value': VALUE_0000000037},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000038': {'address': u'1ADDRESS_00000000000000000000039',
                                                                         'value': VALUE_0000000038},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000039': {'address': u'1ADDRESS_00000000000000000000040',
                                                                         'value': VALUE_0000000039},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000040': {'address': u'1ADDRESS_00000000000000000000041',
                                                                         'value': VALUE_0000000040},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000041': {'address': u'1ADDRESS_00000000000000000000042',
                                                                         'value': VALUE_0000000041},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000042': {'address': u'1ADDRESS_00000000000000000000043',
                                                                         'value': VALUE_0000000042},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000043': {'address': u'1ADDRESS_00000000000000000000044',
                                                                         'value': VALUE_0000000043},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000044': {'address': u'1ADDRESS_00000000000000000000045',
                                                                         'value': VALUE_0000000044},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000045': {'address': u'1ADDRESS_00000000000000000000046',
                                                                         'value': VALUE_0000000045},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000046': {'address': u'1ADDRESS_00000000000000000000047',
                                                                         'value': VALUE_0000000046},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000047': {'address': u'1ADDRESS_00000000000000000000048',
                                                                         'value': VALUE_0000000047},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000048': {'address': u'1ADDRESS_00000000000000000000049',
                                                                         'value': VALUE_0000000048},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000049': {'address': u'1ADDRESS_00000000000000000000050',
                                                                         'value': VALUE_0000000049},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000050': {'address': u'1ADDRESS_00000000000000000000051',
                                                                         'value': VALUE_0000000050},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000051': {'address': u'1ADDRESS_00000000000000000000052',
                                                                         'value': VALUE_0000000051},
 u'TXID_INDEX_00000000000000000000000000000000000000000000000000000052': {'address': u'1ADDRESS_00000000000000000000053',
                                                                         'value': VALUE_0000000052}}
TIMESTAMP_0000000000081 [MainThread  ] [DEBUG]  key=gaplimit
TIMESTAMP_0000000000082 [MainThread  ] [DEBUG]  6
TIMESTAMP_0000000000083 [MainThread  ] [DEBUG]  key=index
TIMESTAMP_0000000000084 [MainThread  ] [DEBUG]  [[80, 65], [2, 122], [0, 79], [0, 50]]
TIMESTAMP_0000000000085 [MainThread  ] [DEBUG]  key=index_cache
TIMESTAMP_0000000000086 [MainThread  ] [DEBUG]  [[0, 0], [0, 0], [0, 0], [0, 0]]
TIMESTAMP_0000000000087 [MainThread  ] [DEBUG]  key=spent_utxos
TIMESTAMP_0000000000088 [MainThread  ] [DEBUG]  []
TIMESTAMP_0000000000089 [MainThread  ] [DEBUG]  key=utxo_selector
TIMESTAMP_0000000000090 [MainThread  ] [DEBUG]  <function select at 0xb643f1b0>
TIMESTAMP_0000000000091 [MainThread  ] [DEBUG]  key=path
TIMESTAMP_0000000000092 [MainThread  ] [DEBUG]  string: len:20
TIMESTAMP_0000000000093 [MainThread  ] [DEBUG]  wallets/tumbler.json
TIMESTAMP_0000000000094 [MainThread  ] [DEBUG]  key=storepassword
TIMESTAMP_0000000000095 [MainThread  ] [DEBUG]  False
TIMESTAMP_0000000000096 [MainThread  ] [DEBUG]  key=max_mix_depth
TIMESTAMP_0000000000097 [MainThread  ] [DEBUG]  4
TIMESTAMP_0000000000098 [MainThread  ] [DEBUG]  key=imported_privkeys
TIMESTAMP_0000000000099 [MainThread  ] [DEBUG]  {0: [CENSORED]}
TIMESTAMP_0000000000100 [MainThread  ] [DEBUG]  Class debug dump, name:Tumbler
TIMESTAMP_0000000000101 [MainThread  ] [DEBUG]  key=tx_list
TIMESTAMP_0000000000102 [MainThread  ] [DEBUG]  [{'amount_fraction': 0.028483490415679324,
  'destination': 'internal',
  'makercount': 4,
  'srcmixdepth': 0,
  'wait': 6.74},
 {'amount_fraction': 0.46643581106578264,
  'destination': 'internal',
  'makercount': 2,
  'srcmixdepth': 0,
  'wait': 25.06},
 {'amount_fraction': 0.5050806985185381,
  'destination': 'internal',
  'makercount': 6,
  'srcmixdepth': 0,
  'wait': 0.79},
 {'amount_fraction': 0.2710870494909247,
  'destination': 'internal',
  'makercount': 2,
  'srcmixdepth': 1,
  'wait': 7.07},
 {'amount_fraction': 0.1760585758837059,
  'destination': 'internal',
  'makercount': 4,
  'srcmixdepth': 1,
  'wait': 94.87},
 {'amount_fraction': 0.5528543746253693,
  'destination': '1ADDRESS_00000000000000000000054',
  'makercount': 3,
  'srcmixdepth': 1,
  'wait': 3.5},
 {'amount_fraction': 0.47763843893256297,
  'destination': 'internal',
  'makercount': 2,
  'srcmixdepth': 2,
  'wait': 22.11},
 {'amount_fraction': 0.291168268294136,
  'destination': 'internal',
  'makercount': 2,
  'srcmixdepth': 2,
  'wait': 117.41},
 {'amount_fraction': 0.231193292773301,
  'destination': '1ADDRESS_00000000000000000000055',
  'makercount': 3,
  'srcmixdepth': 2,
  'wait': 37.91},
 {'amount_fraction': 1.0,
  'destination': '1ADDRESS_00000000000000000000056',
  'makercount': 5,
  'srcmixdepth': 3,
  'wait': 93.42}]
TIMESTAMP_0000000000103 [MainThread  ] [DEBUG]  key=maker_pks
TIMESTAMP_0000000000104 [MainThread  ] [DEBUG]  {}
TIMESTAMP_0000000000105 [MainThread  ] [DEBUG]  key=tumbler_thread
TIMESTAMP_0000000000106 [MainThread  ] [DEBUG]  <TumblerThread(TumblerThread, stopped daemon -1262488480)>
TIMESTAMP_0000000000107 [MainThread  ] [DEBUG]  key=cjtx
TIMESTAMP_0000000000108 [MainThread  ] [DEBUG]  None
TIMESTAMP_0000000000109 [MainThread  ] [DEBUG]  key=db
TIMESTAMP_0000000000110 [MainThread  ] [DEBUG]  <sqlite3.Cursor object at 0xb630fda0>
TIMESTAMP_0000000000111 [MainThread  ] [DEBUG]  key=wallet
TIMESTAMP_0000000000112 [MainThread  ] [DEBUG]  <joinmarket.wallet.Wallet object at 0xb6158a90>
TIMESTAMP_0000000000113 [MainThread  ] [DEBUG]  key=msgchan
TIMESTAMP_0000000000114 [MainThread  ] [DEBUG]  <joinmarket.irc.IRCMessageChannel object at 0xb602f3f0>
TIMESTAMP_0000000000115 [MainThread  ] [DEBUG]  key=options
TIMESTAMP_0000000000116 [MainThread  ] [DEBUG]  {'liquiditywait': 200, 'makercountrange': (3, 1.5), 'mincjamount': 100000, 'mixdepthcount': 4, 'amountpower': 100.0, 'minmakercount': 2, 'txcountparams': (4, 1), 'maxbroadcasts': 4, 'waittime': 30.0, 'txfee': 5000, 'timelambda': 30, 'maxcreatetx': 9, 'mixdepthsrc': 0, 'addrcount': 3, 'maxcjfee': (0.0008, 10000.0), 'donateamount': 0, 'mintxcount': 1}
TIMESTAMP_0000000000117 [MainThread  ] [DEBUG]  Class debug dump, name:NoneType
```

**Comment by chris-belcher** [comment]
Change that line in tumbler.py to say `self.taker.wallet.update_cache_index()` instead of `self.taker.wallet.update_index_cache()` and it will work. I'll be able to fix in a few hours.

**Comment by chris-belcher** [comment]
Fixed and overwrote the tag, so no links need to be updated of the release :)
