### ISSUE TITLE
Crash on received txhex to push

### ISSUE THREAD

**Issue by CohibAA** [JoinMarket-Org/joinmarket#511]
Crash log doesn't seem to show the reason/reply from bitcoin rpc as to why the transaction was not pushed, but I suppose it shouldn't matter, as the [expected behavior is to report the failed push](https://github.com/JoinMarket-Org/joinmarket/blob/master/joinmarket/maker.py#L269-L273).

    2016-05-04 xx:xx:xx,xxx [MainThread  ] [DEBUG]  Traceback (most recent call last):
      File "yield-generator-basic.py", line 237, in main
        irc.run()
      File "/home/redacted/joinmarket/joinmarket/irc.py", line 657, in run
        self.__handle_line(line)
      File "/home/redacted/joinmarket/joinmarket/irc.py", line 540, in __handle_line
        self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
      File "/home/redacted/joinmarket/joinmarket/irc.py", line 491, in __handle_privmsg
        self.__on_privmsg(nick, parsed)
      File "/home/redacted/joinmarket/joinmarket/irc.py", line 393, in __on_privmsg
        self.on_push_tx(nick, txhex)
      File "/home/redacted/joinmarket/joinmarket/maker.py", line 269, in on_push_tx
        if pushed[0]:
    TypeError: 'bool' object has no attribute '__getitem__'

Let me know if anything further from the log would be useful to track this down.

**Comment by AlexCato** [comment]
Same thing, here's another error debug log from the console (4th line looks interesting):
(Also: this is running the version from the developer branch from 2-3 weeks ago)

2016-05-06 01:35:14,098 [MainThread  ] [DEBUG]  <<privmsg nick=SoMeNaMe message=!push [lots of hexnumbers]
2016-05-06 01:35:14,099 [MainThread  ] [DEBUG]  received txhex from SoMeNaMe to push
[long hexnumber]
2016-05-06 01:35:14,099 [MainThread  ] [DEBUG]  rpc: sendrawtransaction ['[long hexnumber]']
{u'message': u'258: txn-mempool-conflict', u'code': -26}
2016-05-06 01:35:14,100 [MainThread  ] [DEBUG]  error pushing = -26 258: txn-mempool-conflict
2016-05-06 01:35:14,100 [MainThread  ] [DEBUG]  CRASHING, DUMPING EVERYTHING
2016-05-06 01:35:14,100 [MainThread  ] [DEBUG]  Class debug dump, name:Wallet
2016-05-06 01:35:14,101 [MainThread  ] [DEBUG]  key=unspent
2016-05-06 01:35:14,105 [MainThread  ] [DEBUG]  {[lots of wallet info]}
2016-05-06 01:35:14,105 [MainThread  ] [DEBUG]  key=gaplimit
2016-05-06 01:35:14,105 [MainThread  ] [DEBUG]  6
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  key=index
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  [[4, 127], [0, 127]]
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  key=index_cache
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  [[4, 123], [0, 123]]
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  key=spent_utxos
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  ['[4 ones]']
2016-05-06 01:35:14,106 [MainThread  ] [DEBUG]  key=utxo_selector
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  <function select_gradual at 0x7f9768b94c80>
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  key=path
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  string: len:23
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  wallets/walletname.json
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  key=storepassword
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  False
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  key=max_mix_depth
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  2
2016-05-06 01:35:14,107 [MainThread  ] [DEBUG]  key=imported_privkeys
2016-05-06 01:35:14,109 [MainThread  ] [DEBUG]  {[some info]}
2016-05-06 01:35:14,109 [MainThread  ] [DEBUG]  Class debug dump, name:YieldGenerator
2016-05-06 01:35:14,109 [MainThread  ] [DEBUG]  key=wallet_unspent_lock
2016-05-06 01:35:14,109 [MainThread  ] [DEBUG]  <_RLock owner=None count=0>
2016-05-06 01:35:14,109 [MainThread  ] [DEBUG]  key=orderlist
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  [[the orderlist]]
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  key=nextoid
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  -1
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  key=wallet
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  <joinmarket.wallet.Wallet object at 0x7f9766476290>
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  key=msgchan
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  <joinmarket.irc.IRCMessageChannel object at 0x7f9766476550>
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  key=income_statement
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  <closed file 'logs/yigen-statement.csv', mode 'a' at 0x7f97662538a0>
2016-05-06 01:35:14,110 [MainThread  ] [DEBUG]  key=tx_unconfirm_timestamp
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  {[three]}
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  key=active_orders
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  {'MyRandomName': None}
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  Class debug dump, name:IRCMessageChannel
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  key=sock
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  <ssl.SSLSocket object at 0x7f976648c578>
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  key=on_push_tx
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_push_tx of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  key=give_up
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  False
2016-05-06 01:35:14,111 [MainThread  ] [DEBUG]  key=lockcond
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  <Condition(<_RLock owner=None count=0>, 0)>
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=given_nick
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  string: len:9
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  Kafoqosid
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=socks5_host
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  string: len:9
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  localhost
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=throttleQ
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  <Queue.Queue instance at 0x7f976646e638>
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=socks5_port
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  9150
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=on_seen_tx
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_seen_tx of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,112 [MainThread  ] [DEBUG]  key=pingQ
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  <Queue.Queue instance at 0x7f976646e6c8>
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=on_nick_change
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=nick
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  string: len:10
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  Kafoqosid_
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=waiting
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  {'SomeRandomName': False, 'MyRandomName': False}
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=on_ioauth
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=obQ
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  <Queue.Queue instance at 0x7f976646e050>
2016-05-06 01:35:14,113 [MainThread  ] [DEBUG]  key=on_seen_auth
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_seen_auth of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=on_orderbook_requested
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_orderbook_requested of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=on_order_fill
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_order_fill of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=on_welcome
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_welcome of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=built_privmsg
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  {}
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=on_order_seen
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=on_error
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,114 [MainThread  ] [DEBUG]  key=ping_reply
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  True
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=cjpeer
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  <__main__.YieldGenerator object at 0x7f9766476850>
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=on_pubkey
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=on_set_topic
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  <function on_set_topic at 0x7f9766479aa0>
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=on_disconnect
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=lockthrottle
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  <Condition(<_RLock owner=None count=0>, 1)>
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=on_connect
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  key=on_nick_leave
2016-05-06 01:35:14,115 [MainThread  ] [DEBUG]  <bound method YieldGenerator.on_nick_leave of <__main__.YieldGenerator object at 0x7f9766476850>>
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=on_sig
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=channel
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  string: len:15
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  #joinmarket-pit
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=serverport
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  ('6dvj6v5imhny3anf.onion', 6698)
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=userrealname
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  ('username', 'btcint=bitcoin-rpc')
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=fd
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  <socket._fileobject object at 0x7f9766bd07d0>
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  key=on_order_cancel
2016-05-06 01:35:14,116 [MainThread  ] [DEBUG]  None
2016-05-06 01:35:14,119 [MainThread  ] [DEBUG]  Traceback (most recent call last):
  File "yield-generator-deluxe.py", line 588, in main
    irc.run()
  File "/home/wolf/Documents/joinmarket-low/joinmarket/irc.py", line 657, in run
    self.__handle_line(line)
  File "/home/wolf/Documents/joinmarket-low/joinmarket/irc.py", line 540, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "/home/wolf/Documents/joinmarket-low/joinmarket/irc.py", line 491, in __handle_privmsg
    self.__on_privmsg(nick, parsed)
  File "/home/wolf/Documents/joinmarket-low/joinmarket/irc.py", line 393, in __on_privmsg
    self.on_push_tx(nick, txhex)
  File "/home/wolf/Documents/joinmarket-low/joinmarket/maker.py", line 269, in on_push_tx
    if pushed[0]:
TypeError: 'bool' object has no attribute '__getitem__'

done

**Comment by chris-belcher** [comment]
doh, this is my fault

ill fix it in a few hours

**Comment by AdamISZ** [comment]
Yeah, got it to. Quick fix is remove the [0] index from if pushed[0] in Maker.on_push_tx ; pushtx now returns either True or False only (it used to return txids).

**Comment by chris-belcher** [comment]
There shouldnt be any reference to txid, that's why i removed it because transaction malleability can always change it.
If you need the tx hash you can use btc.txhash()

Are you saying it affects older versions of joinmarket too? Since i edited what pushtx() does in the develop branch before this last release.

**Comment by AdamISZ** [comment]
Older versions: I was running a just-pre-release develop branch. I could check the exact commit, but I'm sure you know exactly what to do with this anyway.

No ref to txid: ok, makes sense. It was just a quick thought on what to do to get it running again, I understood you were working on a fix, wasn't making any suggestions on the correct code change.

**Comment by chris-belcher** [comment]
fixed and released
