### ISSUE TITLE
IndexError when number of mixdepths in wallet < 5

### ISSUE THREAD

**Issue by nkuttler** [JoinMarket-Org/joinmarket#601]
```
2016-08-06 11:17:32,577 [MainThread  ] [DEBUG]  hello joinmarket
2016-08-06 11:17:32,773 [MainThread  ] [DEBUG]  Estimated transaction size: 372
2016-08-06 11:17:32,773 [MainThread  ] [DEBUG]  rpc: estimatefee [3]
2016-08-06 11:17:32,776 [MainThread  ] [DEBUG]  got estimated tx bytes: 372
2016-08-06 11:17:32,776 [MainThread  ] [DEBUG]  Estimated miner/tx fee for each cj participant: 3821
2016-08-06 11:17:32,776 [MainThread  ] [DEBUG]  starting sendpayment
Enter wallet decryption passphrase: 
2016-08-06 11:17:45,377 [MainThread  ] [DEBUG]  requesting wallet history
Traceback (most recent call last):
  File "/home/nicolas/dev/coin/bitcoin/joinmarket/sendpayment.py", line 338, in <module>
    main()
  File "/home/nicolas/dev/coin/bitcoin/joinmarket/sendpayment.py", line 319, in main
    jm_single().bc_interface.sync_wallet(wallet)
  File "/home/nicolas/dev/coin/bitcoin/joinmarket/joinmarket/blockchaininterface.py", line 78, in sync_wallet
    self.sync_addresses(wallet)
  File "/home/nicolas/dev/coin/bitcoin/joinmarket/joinmarket/blockchaininterface.py", line 617, in sync_addresses
    req_count = int(wallet.index_cache[mix_depth][forchange] /
IndexError: list index out of range
```

An error message would be more useful and could explain to use `-a` or `-m` with `sendpayment.py`or `wallet-tools.py`etc.

**Comment by nkuttler** [comment]
This seems to be the same as #588, closing. I'm on the 0.2.0 branch.
