### ISSUE TITLE
crash in patientsendpayment.py

### ISSUE THREAD

**Issue by peertrade** [JoinMarket-Org/joinmarket#607]
stack trace:

Traceback (most recent call last):
  File "patientsendpayment.py", line 241, in main
    irc.run()
  File "/home/jm/joinmarket/joinmarket/irc.py", line 452, in run
    self.__handle_line(line)
  File "/home/jm/joinmarket/joinmarket/irc.py", line 336, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "/home/jm/joinmarket/joinmarket/irc.py", line 287, in __handle_privmsg
    self.on_privmsg(nick, parsed)
  File "/home/jm/joinmarket/joinmarket/message_channel.py", line 351, in on_privmsg
    self.on_seen_auth(nick, i_utxo_pubkey, btc_sig)
  File "/home/jm/joinmarket/joinmarket/maker.py", line 260, in on_seen_auth
    self.active_orders[nick].auth_counterparty(nick, pubkey, sig)
  File "/home/jm/joinmarket/joinmarket/maker.py", line 103, in auth_counterparty
    btc_pub = btc.privtopub(btc_key)
  File "/home/jm/joinmarket/bitcoin/secp256k1_main.py", line 269, in privkey_to_pubkey
    return privkey_to_pubkey_inner(priv, usehex)
  File "/home/jm/joinmarket/bitcoin/secp256k1_main.py", line 228, in func_wrapper
    newargs += [arg.decode('hex')]
AttributeError: 'NoneType' object has no attribute 'decode'
done

code is from master branch, latest commit: 2ddb54d74a8610f3005e664fddf161290d656242

**Comment by AdamISZ** [comment]
Apologies there has been no response yet. Let me briefly state that patientsendpayment has been broken for a long while, I think (I wasn't involved in coding it), but it hasn't been removed since we want to fix it. Do a search in the issues here, you'll find threads about it. Also, I *think* a certain change in the new 0.2 version will make it more viable, but sorry I don't have time to look right now. In any case, I'll close this until such time it's re-established (and yes sorry for wasting your time, it should not be in the repo if it's not fixed!).
