### ISSUE TITLE
ValueError: Estimated fee per kB greater than absurd value: 150000, quitting.

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#669]
```
Prompt: python sendpayment.py -m1 -N4 --yes wallet.json 1361600 151GjbVwcdue93FPAzvNQCts7CNRLHeUJS
2016-11-25 10:10:43,923 [MainThread  ] [INFO ]  hello joinmarket
2016-11-25 10:10:43,923 [MainThread  ] [INFO ]  Joinmarket directory is: ~/bin/joinmarket-0.2.2
2016-11-25 10:10:44,076 [MainThread  ] [INFO ]  Estimated miner/tx fee for each cj participant: 26003
2016-11-25 10:10:44,076 [MainThread  ] [INFO ]  starting sendpayment
Enter wallet decryption passphrase: 
2016-11-25 10:11:13,570 [MainThread  ] [INFO ]  requesting detailed wallet history from Bitcoin Core client
2016-11-25 10:11:52,879 [MainThread  ] [INFO ]  importing 48080 addresses into account joinmarket-wallet-8177f4
restart Bitcoin Core with -rescan if you're recovering an existing wallet from backup seed
 otherwise just restart this joinmarket script

Prompt:~/bin/joinmarket-0.2.2$ python sendpayment.py --fast -m1 -N4 --yes wallet.json 1369100 1GtDxtsvtwNb2yWvcTNMgu8y2A9x4Dvwir
2016-11-25 16:39:18,855 [MainThread  ] [INFO ]  hello joinmarket
2016-11-25 16:39:18,855 [MainThread  ] [INFO ]  Joinmarket directory is: ~/bin/joinmarket-0.2.2
Traceback (most recent call last):
  File "sendpayment.py", line 429, in <module>
    main()
  File "sendpayment.py", line 381, in main
    options.txfee = max(options.txfee, estimate_tx_fee(2, 2))
  File "~/bin/joinmarket-0.2.2/joinmarket/wallet.py", line 34, in estimate_tx_fee
    str(absurd_fee) + ", quitting.")
ValueError: Estimated fee per kB greater than absurd value: 150000, quitting.
```
It's running against bitcoin-0.13.1.

Anything else I can provide?

**Comment by AdamISZ** [comment]
Do you have tx_fees set to 1 or 2 in joinmarket.cfg? If so, this condition is more likely to occur. My node is reporting extremely high values for these cases:

`estimatefee 2` : 680579
`estimatefee 1` : 2654070 (!)

This will trigger `absurd_fee_per_kb`, which you can reset in the config to a higher value if you like. It's there to protect you.

The default `tx_fees` is 3. This is currently giving: `estimatefee 3` : 76779 , which is a significantly saner value.

**Comment by HamishMacEwan** [comment]
From joinmarket.cfg:
```
#tx fee
tx_fees = 3
```
Thanks for the tip, but if fees are absurd, I'd rather wait. and see.

**Comment by AdamISZ** [comment]
Agreed. I guess it's possible that your node was reporting > 150k at that point. Closing.
