### ISSUE TITLE
joinmarket requires write priveledges into it's executable directory

### ISSUE THREAD

**Issue by ian-kelling** [JoinMarket-Org/joinmarket#696]
For security and to act like proper software that deserves trust, joinmarket should have a directory or two which it writes to, and only the files it needs to write should go in those directories.

Right now, it's compiling the exact same file over and over into it's root directory, which is definitely not necessary.

```
sudo -u bitcoin python wallet-tool.py -p wallet.json
Assembler messages:
Fatal error: can't create ./_noncefunc.o: Permission denied
Traceback (most recent call last):
  File "wallet-tool.py", line 11, in <module>
    from joinmarket import load_program_config, get_network, Wallet, encryptData, \
  File "/a/opt/joinmarket/joinmarket/__init__.py", line 11, in <module>
    from .irc import IRCMessageChannel, B_PER_SEC
  File "/a/opt/joinmarket/joinmarket/irc.py", line 11, in <module>
    from joinmarket.configure import get_config_irc_channel, jm_single
  File "/a/opt/joinmarket/joinmarket/configure.py", line 12, in <module>
    import bitcoin as btc
  File "/a/opt/joinmarket/bitcoin/__init__.py", line 4, in <module>
    from bitcoin.secp256k1_main import *
  File "/a/opt/joinmarket/bitcoin/secp256k1_main.py", line 45, in <module>
    ffi.compile()
  File "/var/lib/bitcoind/.local/lib/python2.7/site-packages/cffi/api.py", line 672, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/var/lib/bitcoind/.local/lib/python2.7/site-packages/cffi/recompiler.py", line 1475, in recompile
    compiler_verbose, debug)
  File "/var/lib/bitcoind/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/var/lib/bitcoind/.local/lib/python2.7/site-packages/cffi/ffiplatform.py", line 65, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by chris-belcher** [comment]
I appreciate this concern. Thanks for opening the issue.

So looks like the libsecp256k1 little files are causing a problem.
