### ISSUE TITLE
sendpayment.py error SELECT COUNT(DISTINCT counterparty) FROM orderbook;

### ISSUE THREAD

**Issue by Onefox** [JoinMarket-Org/joinmarket#707]
i just want to send some coins out of my wallet with:
 python sendpayment.py -m 4 -N 4 wallet.json AMOUNT ADDRESS

I did this plenty of times before but now it stoppt working, 

`2017-02-07 22:41:26,409 [MainThread  ] [INFO ]  hello joinmarket
2017-02-07 22:41:26,409 [MainThread  ] [INFO ]  Joinmarket directory is: /home/joinm/joinmarket-0.2.2
2017-02-07 22:41:26,423 [MainThread  ] [INFO ]  Estimated miner/tx fee for each cj participant: 37742
2017-02-07 22:41:26,424 [MainThread  ] [INFO ]  starting sendpayment
Enter wallet decryption passphrase:
/usr/local/lib/python2.7/dist-packages/secp256k1/__init__.py:228: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  self.ctx, res_compressed, outlen, self.public_key, compflag)
/usr/local/lib/python2.7/dist-packages/secp256k1/__init__.py:506: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  res = func(inst.ctx, key, scalar)
2017-02-07 22:41:29,541 [MainThread  ] [INFO ]  requesting detailed wallet history from Bitcoin Core client
2017-02-07 22:41:36,417 [MainThread  ] [INFO ]  starting sendpayment
2017-02-07 22:41:36,419 [MainThread  ] [INFO ]  starting message channels
2017-02-07 22:41:36,423 [MCThread    ] [INFO ]  connecting to host 6dvj6v5imhny3anf.onion6698
2017-02-07 22:41:36,432 [MCThread    ] [INFO ]  connecting to host cfyfz6afpgfeirst.onion6667
2017-02-07 22:41:40,656 [MCThread    ] [INFO ]  Connected to IRC and joined channel on agora-irc
waiting for all orders to certainly arrive
2017-02-07 22:41:40,866 [MCThread    ] [INFO ]  Connected to IRC and joined channel on CgAn
Exception in thread PaymentThread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "sendpayment.py", line 237, in run
    self.create_tx()
  File "sendpayment.py", line 105, in create_tx
    'SELECT COUNT(DISTINCT counterparty) FROM orderbook;').fetchone()
ProgrammingError: Recursive use of cursors not allowed.`

Than after 4 min its getting some responces:

`2017-02-07 22:45:02,685 [MCThread    ] [INFO ]  <<pubmsg on agora-irc: nick=XXXxpsQMQXvm message=!absoffer 0 83556 68215808 0 508 ~
2017-02-07 22:45:02,818 [MCThread    ] [INFO ]  <<pubmsg on CgAn: nick=XXXxpsQMQXvm message=!absoffer 0 83556 68215808 0 508 ~
2017-02-07 22:45:03,270 [MCThread    ] [INFO ]  <<pubmsg on CgAn: nick=XXXr1QN7UxUW4 message=!absoffer 0 119801 49926755 0 507 ~`

But nothing happens after that

**Comment by AdamISZ** [comment]
This is the second report of this in the last couple of days.

The error is caused by attempting to access the db from two different threads simultaneously. In taker.py I put locks on the db access (self.dblock) because I encountered in testing with multiple message channels that the db access attempts could happen simultaneously. Until now, it wasn't necessary to add the lock in the client scripts like sendpayment, but I presume the actors who have spammed up the orderbook with thousands of orders have slowed down the db access causing this.

Assuming this is all correct, we just need to add `with self.taker.dblock:` in sendpayment, and do similar in any other place there is a db.execute.
