### ISSUE TITLE
"error: [Errno 32] Broken pipe" - Exception happened during processing of request from ('127.0.0.1', 53990)

### ISSUE THREAD

**Issue by HamishMacEwan** [JoinMarket-Org/joinmarket#733]
```
2017-04-16 14:20:41,081 [CoreNotifyTh] [INFO ]  modifying orders. to_cancel=[]
to_announce=[]
127.0.0.1 - - [16/Apr/2017 14:20:41] "HEAD /walletnotify?2d4d7e4d08e6f12e683da4292a2f5baa89224d4c5de9064c12b9fb52f886ea18 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53990)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/username/bin/joinmarket-0.2.3/joinmarket/blockchaininterface.py", line 790, in __init__ 
    self, request, client_address, base_server)
  File "/usr/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocmacewanhketServer.py", line 716, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 279, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```
Any requests for further information or suggestions to remedy problem happily received.

Hamish.

**Comment by chris-belcher** [comment]
Does this happen every time you get a transaction? Which script are you running?

**Comment by HamishMacEwan** [comment]
1. Yes (I've seen it twice, but can't find the log)
2. python yield-generator-basic.py --fast wallet.json

I would offer that the program continues and everything seems fine.  The PC joinmarket is running on is having some intermittent memory allocation problems (at least that's what I take from the error message I sometimes get starting up Screenshot among others.)

**Comment by chris-belcher** [comment]
This will have no effect and can be ignored. I've actually seen it before on my machine but forgot about it.
It seems to happen on these lines https://github.com/JoinMarket-Org/joinmarket/blob/8c2b6d83dfddb85451d185e64f0fe4df62d5c54e/joinmarket/blockchaininterface.py#L867-L876 where it sends the walletnotify message to other joinmarket scripts that might be running.

**Comment by HamishMacEwan** [comment]
> This will have no effect and can be ignored.

The news I love to hear.  Thanks Chris.
