### ISSUE TITLE
 yield-generator-basic.py error each time receiving pubmsg

### ISSUE THREAD

**Issue by kristapsk** [JoinMarket-Org/joinmarket#743]
Tried to run yield-generator-basic.py, connecting to IRC via Tor. It connects to IRC normally (I guess), but each time it receives pubmsg, I got the following error:
```
XXX [MCThread    ] [INFO ]  Connected to IRC and joined channel on CgAn 
XXX [MCThread    ] [INFO ]  <<pubmsg on CgAn: nick=XXX message=!reloffer 0 750000 199962700 1000 0.002 ~
XXX [MCThread    ] [INFO ]  <<pubmsg on CgAn: nick=XXX message=!orderbook
Exception in thread MCThread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "XXX/joinmarket/joinmarket/message_channel.py", line 31, in run
    self.mc.run()
  File "XXX/joinmarket/joinmarket/irc.py", line 448, in run
    self.__handle_line(line)
  File "XXX/joinmarket/joinmarket/irc.py", line 326, in __handle_line
    self.__handle_privmsg(_chunks[0], _chunks[2], get_irc_text(line))
  File "XXX/joinmarket/joinmarket/irc.py", line 278, in __handle_privmsg
    self.on_pubmsg(nick, message)
  File "XXX/joinmarket/joinmarket/message_channel.py", line 889, in on_pubmsg
    self.on_orderbook_requested(nick, self)
  File "XXX/joinmarket/joinmarket/message_channel.py", line 556, in on_orderbook_requested_trigger
    self.on_orderbook_requested(nick, mc)
  File "XXX/joinmarket/joinmarket/maker.py", line 279, in on_orderbook_requested
    self.msgchan.announce_orders(self.orderlist, nick, mc)
  File "XXX/joinmarket/joinmarket/message_channel.py", line 285, in announce_orders
    cmd = orderlist[0]['ordertype']
IndexError: list index out of range

XXX [ThrottleThre] [WARNI]  failed to send ping message on socket
XXX [PingThread  ] [WARNI]  irc ping timed out
XXX [PingThread  ] [INFO ]  errored while trying to quit: error(9, 'Bad file descriptor')
```
(last three lines are repeating forever until I kill it)

Version is 0.2.3.
```
$ git status
HEAD detached at v0.2.3
```

**Comment by AdamISZ** [comment]
>     cmd = orderlist[0]['ordertype']
IndexError: list index out of range

This looks like you don't have any "orders" (or "offers", sorry for continued ambiguity, they're the same thing here). If that's correct, the real bug here is that your yg isn't quitting immediately when it can't create offers, it should.

This could be happening because your bot is not seeing itself having coins (either because it doesn't or due to syncing problems), at least that's what comes to mind.

Sorry this is a vague analysis, I am not at home right now, but I could look again later.

**Comment by kristapsk** [comment]
Apparently, I did not have enough BTC in my wallet. Added some more and now it is not giving errors.
