### ISSUE TITLE
vcvarsall.bat

### ISSUE THREAD

**Issue by Darksheer2017** [JoinMarket-Org/joinmarket#754]
Tried installation on Windows 10 according to readme.md, but vcvarsall.bat problem persists. Any clues?
----------------------
Traceback (most recent call last):
  File "wallet-tool.py", line 11, in <module>
    from joinmarket import load_program_config, get_network, Wallet, encryptData, \
  File "C:\Users\srueh\Desktop\joinmarket-0.2.3\joinmarket\__init__.py", line 11, in <module>
    from .irc import IRCMessageChannel, B_PER_SEC
  File "C:\Users\srueh\Desktop\joinmarket-0.2.3\joinmarket\irc.py", line 11, in <module>
    from joinmarket.configure import get_config_irc_channel, jm_single
  File "C:\Users\srueh\Desktop\joinmarket-0.2.3\joinmarket\configure.py", line 12, in <module>
    import bitcoin as btc
  File "C:\Users\srueh\Desktop\joinmarket-0.2.3\bitcoin\__init__.py", line 4, in <module>
    from bitcoin.secp256k1_main import *
  File "C:\Users\srueh\Desktop\joinmarket-0.2.3\bitcoin\secp256k1_main.py", line 45, in <module>
    ffi.compile()
  File "C:\Python27\lib\site-packages\cffi\api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "C:\Python27\lib\site-packages\cffi\recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "C:\Python27\lib\site-packages\cffi\ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Python27\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "C:\Python27\lib\distutils\command\build_ext.py", line 498, in build_extension
    depends=ext.depends)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 473, in compile
    self.initialize()
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 383, in initialize
    vc_env = query_vcvarsall(VERSION, plat_spec)
  File "C:\Python27\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat

**Comment by moffa13** [comment]
If I remember, think I got it to work by installing this :
https://www.microsoft.com/en-us/download/details.aspx?id=44266

**Comment by AdamISZ** [comment]
@Darksheer2017 according to readme, or according to the wiki page: https://github.com/JoinMarket-Org/joinmarket/wiki/Installing-JoinMarket-on-Windows ?

If the download suggested by @moffa13 is needed perhaps it can be added to the guide. I didn't need it for win7, and had reports the process worked correctly as-is for win 10.
