### ISSUE TITLE
IRC server won't allow Tor connections

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#76]
<a href="https://github.com/dreboli"><img src="https://avatars.githubusercontent.com/u/7959228?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dreboli](https://github.com/dreboli)**
_Friday May 15, 2015 at 22:37 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/chris-belcher/joinmarket/issues/76_

----

Running tumble.py on Whonix gives:
```
starting tumbler
connecting to irc
connecting
>>pubmsg !orderbook
waiting for all orders to certainly arrive
Connected to IRC and joined channel
line was zero length
disconnected irc
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 170, in run
    relorder_fee = float(orders[0])
IndexError: list index out of range

connecting
SSLError(8, '_ssl.c:504: EOF occurred in violation of protocol')
AttributeError("'NoneType' object has no attribute 'close'",)
disconnected irc
```

with usessl = false in joinmarket.cfg the output is:
```
starting tumbler
connecting to irc
connecting
line was zero length
disconnected irc
connecting
line was zero length
disconnected irc
```

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Friday May 15, 2015 at 22:54 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

IRC servers usually ban Tor exit nodes, you have to connect to their onion.

Also it seems the snoonet onion recently went down and they haven't gotten it up yet. Go ask in their main channel (but dont mention joinmarket)

**Comment by AdamISZ** [comment]
<a href="https://github.com/BitpopCoin"><img src="https://avatars.githubusercontent.com/u/7988928?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BitpopCoin](https://github.com/BitpopCoin)**
_Saturday May 16, 2015 at 09:47 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Pretty sad, one of their sysops died a few months back https://www.snoonet.org/updates/26-in-remembrance-of-edify

Also connecting to 443 is much much easier on tor

Port 80 and 443 (For those behind a restrictive firewall)
alt.irc.snoonet.org : 80 (443 for SSL)

They do say tor needs an account though

https://www.snoonet.org/tor

**Comment by AdamISZ** [comment]
<a href="https://github.com/dreboli"><img src="https://avatars.githubusercontent.com/u/7959228?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dreboli](https://github.com/dreboli)**
_Sunday May 17, 2015 at 10:59 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Is there a way to use joinmarket through Tor?

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Sunday May 17, 2015 at 14:28 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Right now no, I've been looking around for IRC networks which allow tor as somewhere to move the pit to. Obviously that's a priority.

Also this is all temporary until another messaging channel that isnt IRC is coded.

**Comment by AdamISZ** [comment]
<a href="https://github.com/BitpopCoin"><img src="https://avatars.githubusercontent.com/u/7988928?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BitpopCoin](https://github.com/BitpopCoin)**
_Sunday May 17, 2015 at 15:16 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

What's an alternative to irc?

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Sunday May 17, 2015 at 23:01 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

https://github.com/cpacia/Subspace

Or maybe tox

**Comment by AdamISZ** [comment]
<a href="https://github.com/BitpopCoin"><img src="https://avatars.githubusercontent.com/u/7988928?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [BitpopCoin](https://github.com/BitpopCoin)**
_Monday May 18, 2015 at 02:06 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

I wonder if this is open source http://www.bleep.pm

**Comment by AdamISZ** [comment]
<a href="https://github.com/adlai"><img src="https://avatars.githubusercontent.com/u/94171?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [adlai](https://github.com/adlai)**
_Monday May 18, 2015 at 02:29 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

@BitpopCoin It's not.

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Monday May 25, 2015 at 01:47 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

With commit https://github.com/chris-belcher/joinmarket/commit/6dbe42ba8f424539424b7b8ecee5631d605ff1f1 we move to an IRC server that allows tor
