### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by fedorkopotnev** [JoinMarket-Org/joinmarket#774]
Hello! I've got error No JSON object could be decoded on wallet showing with:
`python wallet-tool.py wallet1.json`

Full stack trace:
```
2018-01-24 15:47:36,783 [MainThread  ] [INFO ]  hello joinmarket
2018-01-24 15:47:36,783 [MainThread  ] [INFO ]  Joinmarket directory is: /root/jm/joinmarket-0.2.3
Enter wallet decryption passphrase: 
2018-01-24 15:47:38,676 [MainThread  ] [INFO ]  downloading wallet history
Traceback (most recent call last):
  File "wallet-tool.py", line 126, in <module>
    sync_wallet(wallet, fast=options.fastsync)
  File "/root/jm/joinmarket-0.2.3/joinmarket/blockchaininterface.py", line 79, in sync_wallet
    jm_single().bc_interface.sync_wallet(wallet)
  File "/root/jm/joinmarket-0.2.3/joinmarket/blockchaininterface.py", line 88, in sync_wallet
    self.sync_addresses(wallet)
  File "/root/jm/joinmarket-0.2.3/joinmarket/blockchaininterface.py", line 518, in sync_addresses
    data = btc.make_request_blockr(blockr_url + ','.join(addrs))['data']
  File "/root/jm/joinmarket-0.2.3/bitcoin/bci.py", line 41, in make_request_blockr
    data = json.loads(make_request(*args))
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Can you help with this problem?

**Comment by AdamISZ** [comment]
Blockr is not available any more; the site was shut down.

**Comment by fedorkopotnev** [comment]
AdamISZ, thank you! How can I use joinmarket now? Without Blockr API.

**Comment by AdamISZ** [comment]
You should use a full node (pruned is also possible). In the new version of joinmarket there is a fairly reliable implementation of connecting via electrum servers; in this version that is also possible but I didn't put as much work into it; you could try it (set `blockchain_source` in joinmarket.cfg). There is also a blockchain.info implementation, but that is much less likely to work.

If that isn't possible, your options are limited. You could export the private keys (in the new version it's also possible to use the 12 word seed to import into BIP39+49 supporting wallets, but not in this version.

If your situation is as I suspect, your best bet is to try the `electrum` option for `blockchain_source`, but it may be very flaky not least because the electrum server list has not been updated (i.e. you may need to restart it multiple times before it works).

**Comment by AdamISZ** [comment]
Btw for privkey export options read the help with `python wallet-tool.py --help`

**Comment by fedorkopotnev** [comment]
Ok, thanks! I've connect with full node — all OK.
