### ISSUE TITLE
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.

### ISSUE THREAD

**Issue by Talkless** [JoinMarket-Org/joinmarket#776]
Hi,
Using master at time of writing, on:
```
Linux odroid-hc1 4.9.0-7-armmp-lpae #1 SMP Debian 4.9.110-1 (2018-07-05) armv7l GNU/Linux
```
After "Failed to source a commitment", I see this exception:
```
2018-08-03 15:46:49,634 [MainThread  ] [INFO ]  Did not complete successfully, shutting down                                                                 
2018-08-03 15:46:49,634 [MainThread  ] [INFO ]  Taker not continuing after receipt of orderbook                                                    
2018-08-03 15:46:49,635 [MainThread  ] [INFO ]  Did not complete successfully, shutting down                                                       
Unhandled Error                                                                                                                                    
Traceback (most recent call last):                                                                                                                            
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1043, in _commandReceived
    deferred = self.dispatchCommand(box)                                                                                                          
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1101, in dispatchCommand
    return maybeDeferred(responder, box)                                                                                                         
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred 
    result = f(*args, **kw)                                                                                                                      
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/protocols/amp.py", line 1188, in doit          
    return maybeDeferred(aCallable, **kw).addCallback(                                                                                           
--- <exception caught here> ---                                                                                                                    
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred 
    result = f(*args, **kw)                                                                                                                       
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/jmclient/client_protocol.py", line 414, in on_JM_OFFERS
    self.client.on_finished_callback(False, False, 0.0)                                                                               
  File "tumbler.py", line 120, in taker_finished                                                                                      
    reactor.stop()                                                                                                                    
  File "/home/joinmarket/joinmarket-clientserver/jmvenv/local/lib/python2.7/site-packages/twisted/internet/base.py", line 584, in stop
    "Can't stop reactor that isn't running.")                                   
twisted.internet.error.ReactorNotRunning: Can't stop reactor that isn't running.
                                                                 
done                                                        
```

**Comment by AdamISZ** [comment]
Thanks, sigh, looks like I still made an error in that update. It's not consequential, since you were shutting down anyway.

You're more than welcome to just revert to running 0.3.3 since I've screwed this up several times now ...

Your problems with sourcing commitments are unrelated, see IRC.

**Comment by AdamISZ** [comment]
You opened this in the wrong repo @Talkless . No worries I will close and reopen in joinmarket-clientserver

**Comment by Talkless** [comment]
> You opened this in the wrong repo @Talkless 

Ugh, damn, sorry.
