### ISSUE TITLE
wallet-tool.py "Method not found"

### ISSUE THREAD

**Issue by rookey** [JoinMarket-Org/joinmarket#780]
I've just set up JoinMarket and generated wallets/wallet.jmdat (used the default), 
but when entering 
`python wallet-tool.py wallet.jmdat
`I'm receiving fatal error messages:

```
Enter wallet decryption passphrase:
Traceback (most recent call last):
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 504, in sync_addresses
    [wallet_name]))
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 350, in rpc
    res = self.jsonRpc.call(method, args)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/jsonrpc.py", line 160, in call
    raise JsonRpcError(response["error"])
jmclient.jsonrpc.JsonRpcError: {'message': 'Method not found', 'code': -32601}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wallet-tool.py", line 13, in <module>
    jmprint(wallet_tool_main("wallets"), "success")
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/wallet_utils.py", line 1190, in wallet_tool_main
    sync_wallet(wallet, fast=options.fastsync)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 33, in sync_wallet
    jm_single().bc_interface.sync_wallet(wallet)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 402, in sync_wallet
    super(BitcoinCoreInterface, self).sync_wallet(wallet, restart_cb=restart_cb)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 46, in sync_wallet
    self.sync_addresses(wallet, restart_cb)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 506, in sync_addresses
    if wallet_name in self.rpc('listlabels', []):
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/blockchaininterface.py", line 350, in rpc
    res = self.jsonRpc.call(method, args)
  File "/home/admin/joinmarket-clientserver/jmvenv/lib/python3.5/site-packages/jmclient/jsonrpc.py", line 160, in call
    raise JsonRpcError(response["error"])
jmclient.jsonrpc.JsonRpcError: {'message': 'Method not found', 'code': -32601}

```

**Comment by AdamISZ** [comment]
Could you reopen (just copy-paste is fine) this issue in github.com/Joinmarket-Org/joinmarket-clientserver , thanks.
