### ISSUE TITLE
Use itertools.combinations when sweeping

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#81]
<a href="https://github.com/adlai"><img src="https://avatars.githubusercontent.com/u/94171?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adlai](https://github.com/adlai)**
_Tuesday May 19, 2015 at 22:45 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/chris-belcher/joinmarket/pull/81_

----

```
>>> create_combination(['apple', 'orange', 'pear', 'orange'], 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/common.py", line 358, in create_combination
    assert len(result) == nCk(len(li), n)
AssertionError
```

----

_**[adlai](https://github.com/adlai)** included the following code: https://github.com/chris-belcher/joinmarket/pull/81/commits_

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Tuesday May 19, 2015 at 23:06 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Thanks for the PR

Did this cause a crash in a real life usage?

That function is due to be deleted anyway https://github.com/chris-belcher/joinmarket/issues/48

    >>> import itertools
    >>> [i for i in itertools.combinations(['apple', 'orange', 'pear', 'orange'], 3)]
    [('apple', 'orange', 'pear'), ('apple', 'orange', 'orange'), ('apple', 'pear', 'orange'), ('orange', 'pear', 'orange'

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Tuesday May 19, 2015 at 23:12 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

This doesn't actually work out the mathematical correct number for a list with repeated elements. If you're going to use less-than instead of equals you might as well remove the assert totally.
