### ISSUE TITLE
TypeError: choose_order() takes exactly 4 arguments (3 given)

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#86]
<a href="https://github.com/dreboli"><img src="https://avatars.githubusercontent.com/u/7959228?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dreboli](https://github.com/dreboli)**
_Sunday May 24, 2015 at 19:02 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/chris-belcher/joinmarket/issues/86_

----

$python tumbler.py -x 0.003 -w 30 wallet.json address1 address2
...
tumble with these tx? (y/n):y
Enter wallet decryption passphrase: 
[] downloading wallet history
...
connected to IRC
...
coinjoining 2423423424
**Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 189, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 136, in send_tx
    orders, total_cj_fee = choose_order(self.taker.db, amount, tx['makercount'])
TypeError: choose_order() takes exactly 4 arguments (3 given)**

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Sunday May 24, 2015 at 23:08 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Thanks for the bug report, that was a stupid one where the simple checks were forgotten.
