### ISSUE TITLE
AttributeError: 'module' object has no attribute 'choice'

### ISSUE THREAD

**Issue by AdamISZ** [JoinMarket-Org/joinmarket#92]
<a href="https://github.com/dreboli"><img src="https://avatars.githubusercontent.com/u/7959228?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [dreboli](https://github.com/dreboli)**
_Wednesday May 27, 2015 at 10:43 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/chris-belcher/joinmarket/issues/92_

----

$python tumbler.py -x 0.003 -w 30 wallet.json address1 address2
...
tumble with these tx? (y/n):y
Enter wallet decryption passphrase:
[] downloading wallet history
...
connected to IRC
...
coinjoining 2423423424
...
[2015/05/26 15:45:51] randomly choosing orders with weighting
...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "tumbler.py", line 187, in run
    self.send_tx(tx, self.balance_by_mixdepth[tx['srcmixdepth']], sweep)
  File "tumbler.py", line 134, in send_tx
    orders, total_cj_fee = choose_order(self.taker.db, amount, tx['makercount'], weighted_order_choose)
  File "/home/user/joinmarkettor2/lib/common.py", line 365, in choose_order
    chosen_order = chooseOrdersBy(orders, n, lambda k: k[2])
  File "/home/user/joinmarkettor2/lib/common.py", line 323, in weighted_order_choose
    chosen_order_index = np.random.choice(len(orders), p=weight)
AttributeError: 'module' object has no attribute 'choice'

**Comment by AdamISZ** [comment]
<a href="https://github.com/chris-belcher"><img src="https://avatars.githubusercontent.com/u/8398185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chris-belcher](https://github.com/chris-belcher)**
_Wednesday May 27, 2015 at 12:42 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

You need numpy 1.7 or later.

**Comment by AdamISZ** [comment]
<a href="https://github.com/dreboli"><img src="https://avatars.githubusercontent.com/u/7959228?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [dreboli](https://github.com/dreboli)**
_Thursday May 28, 2015 at 20:34 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

----

Yep, was my bad sorry about that.
Thought it was installed but the logs showed the installation failed because python-dev was missing.
